### PR TITLE
optionally include dotfiles in the manifest

### PR DESCRIPTION
**Pull request by anujbiyani**
`Dir['**/**']` ignores dotfiles by default; I have a project that needs some dotfiles to be a part of the bundled gem, so I've changed echoe to use
```ruby
`git ls-files -z`.split("\x0").reject do |f|
  f.match(%r{^(test|spec|features)/})
end
```
which is what Bundler generates when you do `bundle gem gem_name`.

To be backwards compatible, there's a config option `use_git_ls_files` that defaults to `false` in which case `Dir['**/.**']` is used; only when `true` is the new code used.

### CODE REVIEW

**Review by MiroslavCsonka — APPROVED** [review]

**Comment by sgerrand** [comment]
👋  @evan: Would you please review this change.

**Comment by evan** [comment]
Hmm, this project isn't really maintained anymore. @ELLIOTTCABLE are you still doing any reviews or commits?

**Comment by ELLIOTTCABLE** [comment]
@evan unfortunately, not at all — I'd forgotten I'd even been added.

Let me know if there's something specific you'd like of me, I'd love to honour your original efforts in supporting the Ruby community — although to be fair, my Ruby is very rusty!

**Comment by sgerrand** [comment]
@evan @elliotcable: What can I do to assist getting this changeset
reviewed, merged and released?

**Comment by ELLIOTTCABLE** [comment]
@evan As I was just commenting in *another* Ruby project I haven't looked at in ages — I'm a bit out-of-touch with the community, but has Ruby adopted Semver to the capacity that the JavaScript/Node/wasm world has?

If so, perhaps just flip this project over to a ‘all pull-requests merged without review’ status with a semver-major bump? That's pretty good practice for ancient projects; leaves the opportunity for anybody with a vested interest to fork and start doing the maintenance effort.

----

@sgerrand it sounds like neither he nor I have time or wherewithal to thoroughly review this, so the concern is presumably whether this might be breaking behaviour against other dependant parties. The author *does* appear to have added a config-option, and defaulted it to off … in any of my other, more modern projects, I'd simply demand thorough test-coverage, but Echoe doesn't even have any tests. 😵

If @evan has no further input or opinion, and wants to leave it up to me, then I'll take another gander at this issue sometime in the coming week, try and suggest a route forward.

**Comment by anujbiyani** [comment]
> but has Ruby adopted Semver to the capacity that the JavaScript/Node/wasm world has

Ruby is pretty good about Semver, it's widely-accepted.

> but Echoe doesn't even have any tests. 

Heh yeah I didn't feel like strapping a test framework to this when I wrote my code. Maybe I should have...

> so the concern is presumably whether this might be breaking behaviour against other dependant parties. The author does appear to have added a config-option, and defaulted it to off

This _should_ be fully backwards-compatible. Without tests there's no stronger guarantee, unfortunately.

**Comment by evan** [comment]
Seems ok to bump the version and merge with abandon.

**Comment by anujbiyani** [comment]
@sgerrand / @MiroslavCsonka I don't have push access to the FundingCircle repo anymore, but I've updated the version here: https://github.com/anujbiyani/echoe/commit/8f4d48b474af1b0c47745d972e79235df181852e

Feel free to bring the commit over or just redo the work, not like the version-bump-commit is worth anything =)

**Comment by sgerrand** [comment]
👋  @anujbiyani: Done, I updated this changeset with 8f4d48b.

@ELLIOTTCABLE: Let me know when you have time to review this changeset again. I'm happy to discuss this and find a workable solution. 😸

**Pull request closed without merging**
